version: "3.7"

services:
  server:
    build:
      context: ./services/server
      dockerfile: Dockerfile
    volumes:
      - "./services/server:/usr/src/app"
    ports:
      - 5001:5000
    environment:
      - FLASK_ENV=development
      - APP_SETTINGS=api.config.DevelopmentConfig
      - DATABASE_URL=postgres://postgres:postgres@server-db:5432/capital_call_dev
      - DATABASE_TEST_URL=postgres://postgres:postgres@server-db:5432/capital_call_test
    depends_on:
      - server-db

  server-db:
    build:
      context: ./services/server/api/db
      dockerfile: Dockerfile
    ports:
      - 5435:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  client:
    build:
      context: ./services/client
      dockerfile: Dockerfile
    volumes:
      - "./services/client:/usr/src/app"
      - "/usr/src/app/node_modules"
    ports:
      - 3007:3000
    environment:
      - NODE_ENV=development
      - REACT_APP_USERS_SERVICE_URL=http://192.168.99.100:5001
    depends_on:
      - server
